#!/bin/sh

script_dir=$(dirname $0)

echo "Building Server and Client ..."

cd $script_dir/../src/

ghc -o ../build/server Network/TCPServer.hs -main-is Network.TCPServer.main
ghc -o ../build/client Network/TCPClient.hs -main-is Network.TCPClient.main
